# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      "defaults"
      "size=4G"
      "mode=755"
    ];
  };

  #   fileSystems."/" =
  #     { device = "/dev/disk/by-uuid/c5d1544f-439d-4514-96d8-34cbd33e3b79";
  #       fsType = "btrfs";
  #       options = [ "subvol=@root" ];
  #     };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/c5d1544f-439d-4514-96d8-34cbd33e3b79";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/c5d1544f-439d-4514-96d8-34cbd33e3b79";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/c5d1544f-439d-4514-96d8-34cbd33e3b79";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=@persist" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E858-4C2C";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/1019dbb7-0ec8-4b81-b897-98e25cb3d43a"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
